[phases.install]
cmds = [
  'npm install',
  'cd codehub-erp-backend && npm ci --only=production',
  'cd ../frontend && npm install --legacy-peer-deps',
  'cd ../frontend && npm run build'
]

[start]
cmd = 'npm run start:prod'
