[phases.setup]
nixPkgs = ['nodejs', 'npm']

[phases.install]
cmds = [
  'npm ci --only=production --prefix=codehub-erp-backend',
  'npm ci --prefix=frontend',
  'npm run build --prefix=frontend'
]

[phases.build]
cmds = [
  'echo "Build completed"'
]

[start]
cmd = 'npm run start:prod'
